apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse
    isDefault: true
    editable: false
    jsonData:
      host: localhost
      port: 8123
      protocol: http
      username: default
      defaultDatabase: btc
      defaultTable: realtime_market_events
      logs:
        defaultDatabase: btc
        defaultTable: realtime_market_events
        defaultTimeColumn: event_time
      traces:
        defaultDatabase: btc
        defaultTable: realtime_market_events
        defaultDurationTimeColumn: event_time
